version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ".:/app/"
    command: sh -c "sleep 5s && go run ."
    ports:
      - "3000:3000"
    depends_on:
      - database
    tty: True
    networks:
      - app-network
  database:
    image: postgres:14.2-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    tty: True
    networks:
      - app-network
networks:
  app-network:
    driver: bridge